### ISSUE TITLE
Mintsqure and zkSync Portal protocol

### ISSUE THREAD

**Issue by rayaanr** [ByFishh/zk-flow#16]
I have minted an NFT on zkSync using MintSquare, but it is not showing in the Protocol tabs or in the NFT balance list.

<img width="1244" alt="image" src="https://github.com/ByFishh/zk-flow/assets/108685206/19258dbb-47b8-4e10-b6ec-8aac7511d58b">

<img width="901" alt="image" src="https://github.com/ByFishh/zk-flow/assets/108685206/bc9ae4a5-f5b6-4fb4-8c26-8be0bf150aa9">

.

I haven't done any transactions on the zkSync Portal, but it shows as I did one.

<img width="846" alt="image" src="https://github.com/ByFishh/zk-flow/assets/108685206/334adf76-2264-4a6c-bf38-9df51900cdf3">

**Comment by ByFishh** [comment]
Can you send me the transaction tx pls

I just pushed a fix for zkSync era portal :)

**Comment by rayaanr** [comment]
It seems like the portal issue is solved now, and just check it by bridging some funds and the details are accurate. Great work and here's the tx for mintsqute.
https://explorer.zksync.io/tx/0x7b06b0ee3fb11eafd6fd575b4881e0e4ac27ba323b2ca5a5d387252378b62d80

**Comment by rayaanr** [comment]
I have performed some transactions on SpaceFi and Mute as well. Two days ago, those transactions were displayed correctly. However, currently, they are being shown as not interacted in those protocols.

<img width="749" alt="image" src="https://github.com/ByFishh/zk-flow/assets/108685206/9f1da66c-23e8-4623-bc79-959a8d94a059">

**Comment by rayaanr** [comment]
Mintsquare is shutting down on june 30

<img width="587" alt="image" src="https://github.com/ByFishh/zk-flow/assets/108685206/32c16c47-4cd3-45d5-aa6b-7a1e06b36653">
