### ISSUE TITLE
Add Odos dapp

### ISSUE THREAD

**Issue by jdmsu4** [ByFishh/zk-flow#21]
Title
Add Odos dapp

Description
Add the best dex aggregator on zkSync Era to zkFlow

dapp link: https://app.odos.xyz/swap/324/eth/usdc

twitter: https://www.twitter.com/odosprotocol

Router address: https://explorer.zksync.io/address/0xA269031037B4D5fa3F771c401D19E57def6Cb491

Github: https://github.com/odos-xyz/router_v1

ABI: https://api.odos.xyz/info/contract-info/324

**Comment by ByFishh** [comment]
done
