### ISSUE TITLE
Feature Request: Multiple wallets in one page

### ISSUE THREAD

**Issue by parkerburchett** [ByFishh/zk-flow#23]
This is a great tool you've created here!

One feature you might consider adding is a comparison table for multiple wallets. It's common to airdrop farm with multiple wallets and it would be handy to make it easy to see what wallet you've used with each protocol.

Some example tables

| Num interactions | Wallet 1 | Wallet 2 | Wallet 3 |
|------------------|----------|----------|----------|
| dApp 1           |    0     |    2     |    2     |
| dApp 2           |    3     |    2     |    1     |
| dApp 3           |    2     |    0     |    3     |
| dApp 4           |    1     |    0     |    1     |

| Volume in $ | Wallet 1  | Wallet 2  | Wallet 3  |
|-------------|-----------|-----------|-----------|
| dApp 1      |  $278.22  |  $299.37  |  $874.00  |
| dApp 2      |   $0.00   |  $301.25  |  $212.63  |
| dApp 3      |  $963.26  |   $0.00   |  $201.51  |
| dApp 4      |  $251.38  |  $996.91  |   $0.00   |

| Last Activity Date |   Wallet 1   |   Wallet 2   |   Wallet 3   |
|-------------------|--------------|--------------|--------------|
|     dApp 1        | June 2, 2023 | June 5, 2023 | May 4, 2023  |
|     dApp 2        | June 2, 2023 | June 5, 2023 | May 4, 2023  |
|     dApp 3        | June 2, 2023 | June 5, 2023 | May 4, 2023  |
|     dApp 4        | June 2, 2023 | June 5, 2023 | May 4, 2023  |

**Comment by ByFishh** [comment]
done in the new update
