### ISSUE TITLE
Bug or problem

### ISSUE THREAD

**Issue by rm-killer** [ByFishh/zk-flow#24]
Hi bro. Good job with this wallet scan on zksync era.
But there is a bug in the system./ i don't know if i can call it bug or not.
the problem is that the Orbiter finnance transaction and lat time used is incorrect.
mine show i used the orbiter 14 days ago. but im using it more than that and my last use was for today and before that was 3 days ago and before that was 8 days ago and so  on/ so. plz check it.
here is my screen shot about my orbiter history.
![Screenshot 2023-07-17 002102](https://github.com/ByFishh/zk-flow/assets/84083383/b7daae03-1233-44db-bfdb-bb3d71a0dcd3)
![Screenshot 2023-07-17 002004](https://github.com/ByFishh/zk-flow/assets/84083383/e844d17e-6816-4d53-8bb8-aeed9c3517e5)

**Comment by rm-killer** [comment]
no one here to help?

**Comment by ByFishh** [comment]
Hi, zkFlow only handle ETH bridge. I keep it in mind for the next update

**Comment by rm-killer** [comment]
ohhh. didn't know this. ok bro. thanks for your respond.
