### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by guilyx** [ByFishh/zk-flow#25]
Hello, 

I'd like to fork zk-flow and try somethings for another chain, what's the license here ?

Je veux pas faire le rat sans authorisation hihi

Cheers :)

**Comment by ByFishh** [comment]
Yo,

Je vais d'ici quelques semaines changer tout le design avec nouvelles fonctionnalités donc ça risque de pas mal bouger.
Tu peux faire ce que tu veux avec le code mais mentionne moi (twitter/github) et c'est plus sympa si tu fais une PR pour l'intégrer directement à zk-flow :) 

Bien à toi !
