### ISSUE TITLE
Add layer zero dapp

### ISSUE THREAD

**Issue by ByFishh** [ByFishh/zk-flow#4]
### Title

Add layer zero dapp

### Description

Maybe add layer zero app like stargate

**Comment by rayaanr** [comment]
The LayerZeroScan API only provides the ability to retrieve transaction details based on the tx hash. Is there any alternative method available to retrieve txns by address?

And do you have any plan to add StarkNet?

**Comment by ByFishh** [comment]
Find transaction hash on zkSync to layerzero and call layerzero api with this hash 
Atm I don't plan anything, I got a lot of work beside
